# Generated by Django 4.0.2 on 2022-03-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pud_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
